# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: moco_test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      MYSQL_USER: root
      MYSQL_HOST: 127.0.0.1
    steps:
      - checkout
      - run:
          command: sudo apt install -y mysql-client
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "chou/build.gradle" }}-{{ checksum "feeling/build.gradle" }}-{{ checksum "moco/build.gradle" }}-{{ checksum "moco-sample/build.gradle" }}-{{ checksum "moco-test/build.gradle" }}

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "chou/build.gradle" }}-{{ checksum "feeling/build.gradle" }}-{{ checksum "moco/build.gradle" }}-{{ checksum "moco-sample/build.gradle" }}-{{ checksum "moco-test/build.gradle" }}
      - run:
          name: Mysql create table
          command: mysql  -h 127.0.0.1 -u root moco_test < scripts/schema.sql
      # run tests!
      - run: gradle test



